

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."add_story_credits"("user_id_param" "uuid", "amount_param" integer) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  UPDATE users
  SET story_credit = story_credit + amount_param
  WHERE id = user_id_param;
END;
$$;


ALTER FUNCTION "public"."add_story_credits"("user_id_param" "uuid", "amount_param" integer) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."create_quiz_with_questions"("input_story_id" "uuid", "input_user_id" "uuid", "input_total_tokens" integer, "input_questions" "jsonb") RETURNS "uuid"
    LANGUAGE "plpgsql"
    AS $$
declare
  new_quiz_id uuid := uuid_generate_v4();
begin
  -- Insert quiz with user_id and total_tokens
  insert into quizzes (id, story_id, user_id, total_tokens)
  values (new_quiz_id, input_story_id, input_user_id, input_total_tokens);

  -- Insert questions with user_id
  insert into quiz_questions (quiz_id, question, answer, user_id)
  select
    new_quiz_id,
    q->>'question',
    q->>'answer',
    input_user_id
  from jsonb_array_elements(input_questions) as q;

  return new_quiz_id;
end;
$$;


ALTER FUNCTION "public"."create_quiz_with_questions"("input_story_id" "uuid", "input_user_id" "uuid", "input_total_tokens" integer, "input_questions" "jsonb") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."deduct_credit"("user_id" "uuid") RETURNS TABLE("success" boolean)
    LANGUAGE "plpgsql"
    AS $$
begin
  update users
  set story_credit = story_credit - 1
  where id = user_id
    and story_credit > 0
  returning true into success;

  if not found then
    return query select false;
  else
    return query select true;
  end if;
end;
$$;


ALTER FUNCTION "public"."deduct_credit"("user_id" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public', 'auth', 'pg_catalog'
    AS $$
BEGIN
  RAISE NOTICE 'Trigger fired for user: %', NEW.id;

  BEGIN
    INSERT INTO public.users (
      id,
      email,
      role,
      membership_type,
      story_credit,
      tts_credit
    )
    VALUES (
      NEW.id,
      NEW.email,
      COALESCE(NEW.raw_user_meta_data ->> 'role', 'user'),
      COALESCE(NEW.raw_user_meta_data ->> 'membership_type', 'basic'),
      COALESCE((NEW.raw_user_meta_data ->> 'story_credit')::INTEGER, 5),
      COALESCE((NEW.raw_user_meta_data ->> 'tts_credit')::INTEGER, 5)
    );

    RAISE NOTICE 'Successfully created user profile for: %', NEW.id;
  EXCEPTION
    WHEN OTHERS THEN
      RAISE WARNING 'Failed to create user profile for %: % (SQLSTATE: %)', 
        NEW.id, SQLERRM, SQLSTATE;
  END;

  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."increment_num_stories"("user_id" "uuid") RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
begin
  update users
  set num_stories = num_stories + 1
  where id = user_id;
end;
$$;


ALTER FUNCTION "public"."increment_num_stories"("user_id" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."example_stories" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "story" "text"
);


ALTER TABLE "public"."example_stories" OWNER TO "postgres";


ALTER TABLE "public"."example_stories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."example_stories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."feedbacks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "story_id" "uuid" NOT NULL,
    "feedback_data" "jsonb" NOT NULL,
    "user_answer" "text" NOT NULL,
    "target_language" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."feedbacks" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."flashcard_sentences" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "flashcard_id" "uuid" NOT NULL,
    "source_sentence" "text" NOT NULL,
    "target_sentence" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone DEFAULT "now"(),
    "is_learned" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."flashcard_sentences" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."flashcards" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "language_pair" "text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."flashcards" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."plan" (
    "id" integer NOT NULL,
    "productid" integer NOT NULL,
    "productname" "text",
    "variantid" integer NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "price" "text" NOT NULL,
    "isusagebased" boolean DEFAULT false,
    "interval" "text",
    "intervalcount" integer,
    "trialinterval" "text",
    "trialintervalcount" integer,
    "sort" integer,
    "story_credits" integer DEFAULT 0,
    "image_url" "text"
);


ALTER TABLE "public"."plan" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."plan_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."plan_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."plan_id_seq" OWNED BY "public"."plan"."id";



CREATE TABLE IF NOT EXISTS "public"."quiz_questions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "quiz_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "question" "text" NOT NULL,
    "answer" "text" NOT NULL,
    "user_id" "uuid"
);


ALTER TABLE "public"."quiz_questions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."quizzes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "story_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "total_tokens" numeric NOT NULL,
    "user_id" "uuid"
);


ALTER TABLE "public"."quizzes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."stories" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "english_version" "text",
    "translated_version" "text",
    "level" "text",
    "length" "text",
    "total_tokens" numeric,
    "user_id" "uuid" DEFAULT "gen_random_uuid"(),
    "translate_to" "text" NOT NULL,
    "title" "text",
    "feedback_generated" boolean DEFAULT false
);


ALTER TABLE "public"."stories" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."subscriptions" (
    "id" bigint NOT NULL,
    "lemon_squeezy_id" "text" NOT NULL,
    "order_id" integer NOT NULL,
    "name" "text" NOT NULL,
    "email" "text" NOT NULL,
    "status" "text" NOT NULL,
    "status_formatted" "text" NOT NULL,
    "renews_at" "text",
    "ends_at" "text",
    "trial_ends_at" "text",
    "price" "text" NOT NULL,
    "is_usage_based" boolean DEFAULT false,
    "is_paused" boolean DEFAULT false,
    "subscription_item_id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "plan_id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."subscriptions" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."subscriptions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."subscriptions_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."subscriptions_id_seq" OWNED BY "public"."subscriptions"."id";



CREATE SEQUENCE IF NOT EXISTS "public"."subscriptions_subscription_item_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."subscriptions_subscription_item_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."subscriptions_subscription_item_id_seq" OWNED BY "public"."subscriptions"."subscription_item_id";



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" "text",
    "role" "text" DEFAULT 'user'::"text",
    "story_credit" numeric DEFAULT '3'::numeric,
    "tts_credit" numeric DEFAULT '3'::numeric,
    "membership_type" "text",
    "num_stories" numeric DEFAULT '0'::numeric
);


ALTER TABLE "public"."users" OWNER TO "postgres";


COMMENT ON COLUMN "public"."users"."membership_type" IS 'basic';



COMMENT ON COLUMN "public"."users"."num_stories" IS 'Number of stories user created';



CREATE TABLE IF NOT EXISTS "public"."webhook_events" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "event_name" "text" NOT NULL,
    "processed" boolean DEFAULT false,
    "body" "jsonb" NOT NULL,
    "processing_error" "text"
);


ALTER TABLE "public"."webhook_events" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."webhook_events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."webhook_events_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."webhook_events_id_seq" OWNED BY "public"."webhook_events"."id";



ALTER TABLE ONLY "public"."plan" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."plan_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."subscriptions" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."subscriptions_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."subscriptions" ALTER COLUMN "subscription_item_id" SET DEFAULT "nextval"('"public"."subscriptions_subscription_item_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."webhook_events" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."webhook_events_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."example_stories"
    ADD CONSTRAINT "example_stories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."feedbacks"
    ADD CONSTRAINT "feedbacks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."flashcard_sentences"
    ADD CONSTRAINT "flashcard_sentences_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."flashcards"
    ADD CONSTRAINT "flashcards_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."plan"
    ADD CONSTRAINT "plan_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."plan"
    ADD CONSTRAINT "plan_variantid_key" UNIQUE ("variantid");



ALTER TABLE ONLY "public"."quiz_questions"
    ADD CONSTRAINT "quiz_questions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."quizzes"
    ADD CONSTRAINT "quizzes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."stories"
    ADD CONSTRAINT "stories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_lemon_squeezy_id_key" UNIQUE ("lemon_squeezy_id");



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."webhook_events"
    ADD CONSTRAINT "webhook_events_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_feedbacks_created_at" ON "public"."feedbacks" USING "btree" ("created_at" DESC);



CREATE INDEX "idx_feedbacks_story_id" ON "public"."feedbacks" USING "btree" ("story_id");



CREATE INDEX "idx_feedbacks_user_id" ON "public"."feedbacks" USING "btree" ("user_id");



CREATE INDEX "idx_stories_user_created" ON "public"."stories" USING "btree" ("user_id", "created_at" DESC);



CREATE INDEX "idx_subscriptions_lemon_squeezy_id" ON "public"."subscriptions" USING "btree" ("lemon_squeezy_id");



CREATE INDEX "idx_subscriptions_plan_id" ON "public"."subscriptions" USING "btree" ("plan_id");



CREATE INDEX "idx_subscriptions_status" ON "public"."subscriptions" USING "btree" ("status");



CREATE INDEX "idx_subscriptions_user_id" ON "public"."subscriptions" USING "btree" ("user_id");



CREATE INDEX "idx_webhook_events_created_at" ON "public"."webhook_events" USING "btree" ("created_at" DESC);



CREATE INDEX "idx_webhook_events_event_name" ON "public"."webhook_events" USING "btree" ("event_name");



CREATE INDEX "idx_webhook_events_processed" ON "public"."webhook_events" USING "btree" ("processed") WHERE ("processed" = false);



CREATE OR REPLACE TRIGGER "update_feedbacks_updated_at" BEFORE UPDATE ON "public"."feedbacks" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



ALTER TABLE ONLY "public"."feedbacks"
    ADD CONSTRAINT "feedbacks_story_id_fkey" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."feedbacks"
    ADD CONSTRAINT "feedbacks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."flashcard_sentences"
    ADD CONSTRAINT "flashcard_sentences_flashcard_id_fkey" FOREIGN KEY ("flashcard_id") REFERENCES "public"."flashcards"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."flashcards"
    ADD CONSTRAINT "flashcards_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."quiz_questions"
    ADD CONSTRAINT "quiz_questions_quiz_id_fkey" FOREIGN KEY ("quiz_id") REFERENCES "public"."quizzes"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."quiz_questions"
    ADD CONSTRAINT "quiz_questions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."quizzes"
    ADD CONSTRAINT "quizzes_story_id_fkey" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."quizzes"
    ADD CONSTRAINT "quizzes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."stories"
    ADD CONSTRAINT "stories_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "public"."plan"("id");



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");



CREATE POLICY "Allow user to read their own data" ON "public"."users" FOR SELECT USING (("auth"."uid"() = "id"));



CREATE POLICY "Enable delete for users based on user_id" ON "public"."flashcards" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable delete for users based on user_id" ON "public"."stories" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."flashcard_sentences" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."webhook_events" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users with admin role" ON "public"."plan" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."users"
  WHERE (("users"."id" = "auth"."uid"()) AND ("users"."role" = 'admin'::"text")))));



CREATE POLICY "Enable insert for users based on user_id" ON "public"."flashcards" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable insert for users based on user_id" ON "public"."quiz_questions" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable insert for users based on user_id" ON "public"."quizzes" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable insert for users based on user_id" ON "public"."stories" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable insert for users based on user_id" ON "public"."subscriptions" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable read access for all users" ON "public"."example_stories" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."flashcard_sentences" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."plan" FOR SELECT USING (true);



CREATE POLICY "Enable update for users based on email" ON "public"."users" FOR UPDATE USING (((( SELECT "auth"."jwt"() AS "jwt") ->> 'email'::"text") = "email")) WITH CHECK (((( SELECT "auth"."jwt"() AS "jwt") ->> 'email'::"text") = "email"));



CREATE POLICY "Enable users to view their own data only" ON "public"."flashcards" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable users to view their own data only" ON "public"."quiz_questions" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable users to view their own data only" ON "public"."quizzes" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable users to view their own data only" ON "public"."stories" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Users can insert their own feedback" ON "public"."feedbacks" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update their own stories" ON "public"."stories" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can view their own feedback" ON "public"."feedbacks" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "admin can update this table" ON "public"."plan" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM "public"."users"
  WHERE (("users"."id" = "auth"."uid"()) AND ("users"."role" = 'admin'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."users"
  WHERE (("users"."id" = "auth"."uid"()) AND ("users"."role" = 'admin'::"text")))));



CREATE POLICY "all can write to table" ON "public"."example_stories" FOR INSERT WITH CHECK (false);



ALTER TABLE "public"."example_stories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."feedbacks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."flashcard_sentences" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."flashcards" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "let user update " ON "public"."flashcard_sentences" FOR UPDATE USING (true);



ALTER TABLE "public"."plan" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."quiz_questions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."quizzes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."stories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."subscriptions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."webhook_events" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."add_story_credits"("user_id_param" "uuid", "amount_param" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."add_story_credits"("user_id_param" "uuid", "amount_param" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."add_story_credits"("user_id_param" "uuid", "amount_param" integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."create_quiz_with_questions"("input_story_id" "uuid", "input_user_id" "uuid", "input_total_tokens" integer, "input_questions" "jsonb") TO "anon";
GRANT ALL ON FUNCTION "public"."create_quiz_with_questions"("input_story_id" "uuid", "input_user_id" "uuid", "input_total_tokens" integer, "input_questions" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_quiz_with_questions"("input_story_id" "uuid", "input_user_id" "uuid", "input_total_tokens" integer, "input_questions" "jsonb") TO "service_role";



GRANT ALL ON FUNCTION "public"."deduct_credit"("user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."deduct_credit"("user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."deduct_credit"("user_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."increment_num_stories"("user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."increment_num_stories"("user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."increment_num_stories"("user_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "service_role";


















GRANT ALL ON TABLE "public"."example_stories" TO "anon";
GRANT ALL ON TABLE "public"."example_stories" TO "authenticated";
GRANT ALL ON TABLE "public"."example_stories" TO "service_role";



GRANT ALL ON SEQUENCE "public"."example_stories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."example_stories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."example_stories_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."feedbacks" TO "anon";
GRANT ALL ON TABLE "public"."feedbacks" TO "authenticated";
GRANT ALL ON TABLE "public"."feedbacks" TO "service_role";



GRANT ALL ON TABLE "public"."flashcard_sentences" TO "anon";
GRANT ALL ON TABLE "public"."flashcard_sentences" TO "authenticated";
GRANT ALL ON TABLE "public"."flashcard_sentences" TO "service_role";



GRANT ALL ON TABLE "public"."flashcards" TO "anon";
GRANT ALL ON TABLE "public"."flashcards" TO "authenticated";
GRANT ALL ON TABLE "public"."flashcards" TO "service_role";



GRANT ALL ON TABLE "public"."plan" TO "anon";
GRANT ALL ON TABLE "public"."plan" TO "authenticated";
GRANT ALL ON TABLE "public"."plan" TO "service_role";



GRANT ALL ON SEQUENCE "public"."plan_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."plan_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."plan_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."quiz_questions" TO "anon";
GRANT ALL ON TABLE "public"."quiz_questions" TO "authenticated";
GRANT ALL ON TABLE "public"."quiz_questions" TO "service_role";



GRANT ALL ON TABLE "public"."quizzes" TO "anon";
GRANT ALL ON TABLE "public"."quizzes" TO "authenticated";
GRANT ALL ON TABLE "public"."quizzes" TO "service_role";



GRANT ALL ON TABLE "public"."stories" TO "anon";
GRANT ALL ON TABLE "public"."stories" TO "authenticated";
GRANT ALL ON TABLE "public"."stories" TO "service_role";



GRANT ALL ON TABLE "public"."subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."subscriptions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."subscriptions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."subscriptions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."subscriptions_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."subscriptions_subscription_item_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."subscriptions_subscription_item_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."subscriptions_subscription_item_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON TABLE "public"."webhook_events" TO "anon";
GRANT ALL ON TABLE "public"."webhook_events" TO "authenticated";
GRANT ALL ON TABLE "public"."webhook_events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."webhook_events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."webhook_events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."webhook_events_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























